### Send POST request with json body
POST http://localhost:8080/value
Content-Type: application/json

{
  "id": "PollCount",
  "type": "counter"
}

### Send POST request with json body
POST http://localhost:8080/update/unknown/testCounter/100
Content-Type: text/plain

### Send POST request with json body
POST http://localhost:8080/update
Content-Type: application/json

{
  "id": "PollCount",
  "type": "counter",
  "delta": 123,
  "hash": "1acb52da5252030283d8b097c557a49fe4f5ba896537767bff60fbe7298f2325"
}

### GET request with a header
GET http://localhost:8080/
Accept: html/text
