### Send POST request with json body
POST http://localhost:8080/value/
Content-Type: application/json

{
  "id": "GetSet58",
  "type": "counter"
}

### Send POST request with json body
POST http://localhost:8080/update/unknown/testCounter/100
Content-Type: text/plain

### Send POST request with json body
POST http://localhost:8080/update
Content-Type: application/json

{
  "id": "GetSet58",
  "type": "counter",
  "delta": 824633880584,
  "hash": ""
}

### GET request with a header
GET http://localhost:8080/
Accept: html/text

### Send POST request with json body
POST http://localhost:8080/update/counter/testCounter/100
Content-Type: text/plain
X-Real-IP: 192.168.2.1